apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: app
    matchExpressions:
      - { key: app, operator: In, values: [app, second-app] }
  template:
    metadata:
      labels:
        app: app
      spec:
        containers:
          - name: node
            image: registry/app-image
