apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      spec:
        containers:
          - name: node
            image: registry/app-image
